# Perfil de velocidad de Blasius

En clases derivamos la ecuación de Blasius para el perfil de velocidad dentro de la capa límite sobre una placa plana:

\begin{equation}
f'''+\frac{1}{2}ff''=0
\end{equation}

donde sabemos que

\begin{align}
f'(\eta) = \frac{u}{U_\infty}\\
\eta = y\left(\frac{U_\infty}{\nu x}\right)^{1/2}
\end{align}

y las condiciones de borde

\begin{align}
f'(0) = 0\\
f'(\infty) = 1\\
f(0) = 0
\end{align}

En $\eta$, la coordenada $x$ corre paralela a la placa plana e $y$ perpendicular a esta.



## Espesor de capa límite a partir de la ecuación de Blasius

La derivación de Blasius nos dejó con una ecuación diferencial ordinaria de tercer orden, donde la función $f$ depende de solamente una variable ($\eta$). A continuación presentamos un pequeño código que integra la ecuación diferencial numéricamente (utilizando método de Euler de primer orden), para encontrar la solución para $f$, y, por ende, $f'$ y $u(y)$.

El método de Euler integra numéricamente de la siguiente manera

\begin{equation}
F^{n+1} = F^n + h F'^n
\end{equation}

Escribamos una función que haga la iteración de Euler

In [1]:
import numpy

def Euler(F, N, h):
    for i in range(N):
        k1 = h * f_prima(F[i,:])
        F[i+1,:] = F[i,:] + k1
    
    return F

En este caso, $F$ será el vector

\begin{equation}
F = \left(
\begin{array}{c}
f\\
f'\\
f''\\
\end{array}
\right)
\end{equation}

por lo que $F'$ es

\begin{equation}
F' = \left(
\begin{array}{c}
f'\\
f''\\
f'''\\
\end{array}
\right)
\end{equation}

Pero por la ecuación de Blasius, podemos escribir $f'''=-\frac{1}{2}ff''$, y $F'$ queda

\begin{equation}
F' = \left(
\begin{array}{c}
f'\\
f''\\
-\frac{1}{2}ff''\\
\end{array}
\right)
\end{equation}

In [3]:
def f_prima(F):
    return numpy.array([F[1], F[2], -F[2]*F[0]/2])

La ecuación de Blasius es de tercer orden y tenemos tres condiciones de contorno, por lo que deberíamos ser capaces de resolver la ecuación, sin embargo, una de esas condiciones está situada al "final" de nuestra evaluación. Para resolver este problema numéricamente usaremos la técnica de *shooting*: buscar la condición de contorno en $f''(0)$ tal que se cumpla la condición $f'(\infty) = 1$. 

El punto $\eta\to\infty$ está lejos de la placa. Consideremos que $\eta=10$ ya está suficientemente lejos, y $f'(10)\approx1$.

Con prueba y error (no muy eficiente!) encuentre la condición de contorno $f''(0)$ que cumple con $f'(10)\approx1$.

In [19]:
L = 10.
N = 100000
n = 3

U_inf = 1.

a = 0
b = L
h = (b-a)/N

z = numpy.arange(a,b+h,h)
F = numpy.zeros((N+1, n))

Fpp_0 = 0.332
F[0,:] = [0., 0., Fpp_0] # Condicion de contorno

F = Euler(F,N,h)

u = F[:,1]*U_inf

print (r'eta u')
for i in range(N+1):
    if (i%100)==0:
        #print ('{0} {1}'.format(z[i], u[i]))
        print('%1.3f\t%1.9f'%(z[i],u[i]))

F[0]

eta u
0.000	0.000000000
0.010	0.003320000
0.020	0.006640000
0.030	0.009959998
0.040	0.013279994
0.050	0.016599986
0.060	0.019919971
0.070	0.023239945
0.080	0.026559907
0.090	0.029879850
0.100	0.033199772
0.110	0.036519666
0.120	0.039839526
0.130	0.043159347
0.140	0.046479122
0.150	0.049798842
0.160	0.053118501
0.170	0.056438089
0.180	0.059757598
0.190	0.063077017
0.200	0.066396337
0.210	0.069715547
0.220	0.073034636
0.230	0.076353591
0.240	0.079672401
0.250	0.082991053
0.260	0.086309532
0.270	0.089627826
0.280	0.092945918
0.290	0.096263795
0.300	0.099581441
0.310	0.102898839
0.320	0.106215973
0.330	0.109532825
0.340	0.112849378
0.350	0.116165612
0.360	0.119481510
0.370	0.122797052
0.380	0.126112217
0.390	0.129426985
0.400	0.132741335
0.410	0.136055245
0.420	0.139368693
0.430	0.142681657
0.440	0.145994112
0.450	0.149306036
0.460	0.152617403
0.470	0.155928190
0.480	0.159238370
0.490	0.162547918
0.500	0.165856807
0.510	0.169165010
0.520	0.172472499
0.530	0.175779247
0.540	0.179085225
0.55

array([0.   , 0.   , 0.332])

In [22]:
print(F)
print(F[-1,:])
print(z[-1]-F[-1,0])

[[0.00000000e+00 0.00000000e+00 3.32000000e-01]
 [0.00000000e+00 3.32000000e-05 3.32000000e-01]
 [3.32000000e-09 6.64000000e-05 3.32000000e-01]
 ...
 [8.27817186e+00 9.99920156e-01 8.44786213e-09]
 [8.27827185e+00 9.99920156e-01 8.44436549e-09]
 [8.27837184e+00 9.99920156e-01 8.44087025e-09]]
[8.27837184e+00 9.99920156e-01 8.44087025e-09]
1.721628160131802


In [ ]:
delta_x = 4.92/numpy.sqrt(Rex)

Usando el resultado anterior, encuentren una expresión para $\frac{delta}{x}$ ¿Cómo se compara con von Kármán?

## Espesor de desplazamiento

Ya vimos en clases que la definición del espesor de desplazamiento es

\begin{equation}
\delta^* = \int_0^\infty\left(1-\frac{u(y)}{U_\infty}\right)dy
\end{equation}

lo cual podemos reescribir en términos de $f(\eta)$, con $dy = d\eta\left(\frac{\nu x}{U_\infty}\right)^{1/2}$

\begin{align}
\delta^* &= \left(\frac{\nu x}{U_\infty}\right)^{1/2}\int_0^\infty(1-f'(\eta))d\eta\\
& = \left.\left(\frac{\nu x}{U_\infty}\right)^{1/2} (\eta-f(\eta))\right|_\infty
\end{align}

Usando los cálculos numéricos encuentre una expresión para $\frac{\delta^*}{x}$, y compare con lo que obtuvimos con von Kármán.

In [23]:
print(z[-1]-F[-1,0])

1.721628160131802


Ven como tiende al valor $\eta-f(\eta)=1.721$ hacia el infinito? Viendo la ecuación anterior para $\delta^*$ y dividiendo por $x$, llegamos a

\begin{equation}
\frac{\delta^*}{x} = \frac{1.721}{\sqrt{Re_x}}
\end{equation}

## Esfuerzo cortante

Sabemos que la definición de $\tau_w$ es

\begin{equation}
\tau_w = \left.\mu\frac{du}{dy}\right|_0
\end{equation}

lo cual se puede escribir en términos de $f$ y $\eta$ como

\begin{equation}
\tau_w = \left. U_\infty\mu \frac{df'}{dy}\right|_0 = U_\infty\mu \left(\frac{U_\infty}{\nu x}\right)^{1/2}f''(0) = U_\infty^{3/2}\left(\frac{\mu\rho}{x}\right)^{1/2}f''(0) 
\end{equation}

Encuentre una expresión para $\tau_w$ y $c_f$.


## Espesor de momentum

La relación integral de momentum dice que

\begin{equation}
\tau_w = \rho U_\infty^2 \frac{d\theta}{dx}
\end{equation}

Use la expresión recién encontrada para $\tau_w$ para encontrar una expresión para $\frac{\theta}{x}$

$$f''(0) = 0.332$$ 
\begin{equation}
\tau_w = 0.332 U_{\infty}^{3/2} \left(\frac{\mu \rho}{x}\right)^{1/2}
\end{equation}

$$c_f = \frac{0.664}{\sqrt{Re_x}}$$

$$\frac{\theta}{x} = \frac{0.664}{\sqrt{Re_x}}$$